[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Neovim Config"
path = "~/src/dotfiles-mac/neovim/.config/nvim"
startup_command = "nvim"
preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "GitHub Dashboard"
path = "~/src"
startup_command = "gh dash"
