#!/usr/bin/env bash

source ~/.bash/bash_aliases
source ~/.bash/fzf_related
source ~/.bash/utilities source ~/.bash/google_cloud
source ~/.bash/k8s

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Set Vi Mode
set -o vi
bindkey "^R" history-incremental-search-backward
bindkey '^x^e' edit-command-line

export REVIEW_BASE=master
export NVM_DIR="/Users/sendhil/.nvm"

export BAT_THEME="TwoDark"
export PATH=/opt/homebrew/bin:~/.cargo/bin:$GOPATH/bin:$GOROOT/bin:~/src/google-cloud-sdk/bin:~/.local/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:~/Library/Python/3.9/bin:~/go/bin:$PATH
export LESS=FRX

# VirtualEnv
if [ -f ~/.local/bin/virtualenvwrapper_lazy.sh ]; then
  export WORKON_HOME=$HOME/.virtualenvs
  export PROJECT_HOME=$HOME/src
  source ~/.local/bin/virtualenvwrapper_lazy.sh
fi

# Colored Man Pages
export MANPAGER='nvim +Man!'


if [[ $TERM = 'xterm-kitty' ]]; then
  # Dynamic Kitty Themes (Source - https://evantravers.com/articles/2019/07/30/toggling-kitty-and-neovim-background-using-osx-s-dark-mode-setting/)
  if [[ ( $(darkMode) =~ 'Dark' ) ]]; then
    kitty @ set-colors --all --configured ~/.config/kitty/themes/Nord.conf
  else
    kitty @ set-colors --all --configured ~/.config/kitty/themes/Nord.conf
    # kitty @ set-colors --all --configured ~/.config/kitty/themes/Solarized\ Light.conf
  fi
fi

# Load PyEnv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

if [ -f ~/.bash_local ]; then
  source ~/.bash_local
fi
